server:
  port: ${SERVICE_PORT:7021}
  servlet:
    context-path: /${SERVICE_NAME:demo}
spring:
  application:
    name: ${SERVICE_NAME:demo}
  config:
    use-legacy-processing: true
  profiles:
    include: >
    db
  liquibase:
    change-log: classpath:/db/changelog/rootChangeLog.xml
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      hibernate:
        naming:
          physical-strategy: ru.diasoft.micro.lib.config.H2PhysicalNamingStrategy

